name: Test Build
description: Checks whether the app can be built successfully

inputs:
  node-version:
    description: 'NodeJS version to use'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }} 
          cache: npm

      - name: Install Packages
        run: npm ci
        shell: bash

      - name: Build App
        run: npm run build > log.txt
        shell: bash

      # have an eye on https://github.com/actions/runner/issues/662 to avoid the if statements
      - if: failure()
        uses: mshick/add-pr-comment@v2
        with:
          message-path: log.txt
          preformatted: true
          refresh-message-position: true
          allow-repeats: true
